### ISSUE TITLE
Blank thumbnail images and blank page in blog/all

### ISSUE THREAD

**Issue by manacim** [ColdTrick/blog_tools#21]
2015/01/31 09:23:12 [error] 3239#0: *123 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Elgg_EntityDirLocator' not found in /usr/share/nginx/html/mod/blog_tools/pages/thumbnail.php on line 63" while reading response header from upstream, client: 73.12.140.70, server: 127.0.0.1, request: "GET /mod/blog_tools/pages/thumbnail.php?guid=10620&blog_guid=15029&size=medium&icontime=1414615350 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "demyx.com", referrer: "http://demyx.com/activity"

**Comment by jeabakker** [comment]
which version of Elgg are you using? and which version of blog_tools

**Comment by manacim** [comment]
Elgg 1.10.1
Blog Tools 1.9 Release 3.1

**Comment by jeabakker** [comment]
they changes the Elgg classes to be namespaced. I'll need to fix this and release a 1.10 version.

will come soon (-ish)

**Comment by manacim** [comment]
Ah I see, ok thanks.

**Comment by jeabakker** [comment]
fixed now, will release a 1.10 version soon. but you can use the github version for now
