### ISSUE TITLE
Problems removing Blog widget in groups

### ISSUE THREAD

**Issue by insideth** [ColdTrick/blog_tools#22]
If I remove this widget, when I edit the group the widget is enabled by itself. Sometimes it is duplicated in the group dashboard if I edit the group again. 

I´m with Elgg 1.9.8 and Widget Manager 5.0. I´ve tested with all 3rd party plugins disabled except Widget Manager, and Blog Tools, so I think is a incompatibility with these plugins.

![image](https://cloud.githubusercontent.com/assets/6679837/6233187/84c5d9ae-b6d1-11e4-9dc3-bbe87c1d2f62.png)

**Comment by jdalsem** [comment]
This is related to a group tools feature. See https://github.com/ColdTrick/group_tools/issues/79#issuecomment-163912134
