### ISSUE TITLE
Feature request - Add to blog

### ISSUE THREAD

**Issue by Westlake56** [ColdTrick/blog_tools#23]
In many blogs, the one on elgg is a good example. http://blog.elgg.org/ rather than having a new and separate blog entries are added to the existing blog. Where I would use this as an example is adding entries while on vacation, Date: did this, saw that or whatever.

Since they already have that feature as part of the blog on elgg.org, I'm surprise it isn't already a feature.

**Comment by jdalsem** [comment]
i do not understand what feature you are requesting here...

**Comment by Westlake56** [comment]
Sorry for not explaining it properly.
Currently in elgg with a blog the only way to add to it is by editing the existing entry, not add a new entry to an existing blog like they show in the blog on the elgg site for new releases of elgg.

Say I'm on vacation so the blog is our vacation and then for the different dates I want to add to it. In Activity it would then show it has been updated so if anyone is following our travels they know to visit the blog.

I hope this explains it properly.

![elgg blog](https://cloud.githubusercontent.com/assets/11148775/6553197/88873904-c624-11e4-94a6-34b260a5a92d.png)

**Comment by jdalsem** [comment]
i'm not sure why you want to add to a blog post. You can just create new blogs. There is a conceptual difference between a blog (as a collection of different posts) and a blog post (how Elgg handles it). Every post/item is done as a person or in a group. So if you want your vacation blogs listed, you go to yoursite.com/blog/owner/username. There you will find all your posts listed chronologically. So i think you are using it incorrectly and it is not a feature you are missing.
