### ISSUE TITLE
Remove Blog Icon

### ISSUE THREAD

**Issue by Pasley70** [ColdTrick/blog_tools#24]
Currently you can’t remove a Blog Icon. Wish: Is it possible to add a checkbox "Remove Icon"?

**Comment by jdalsem** [comment]
it should be there... looking into it now

**Comment by jdalsem** [comment]
![screenshot blog icon remove](https://cloud.githubusercontent.com/assets/861833/6727169/b8edcf10-ce1f-11e4-9669-b5318eb7f5d1.png)

it should be there as seen in the screenshot, so i assume for now it is an other plugin that overrides the form or something. Also check your plugin order (blog tools should be after blog).

**Comment by Pasley70** [comment]
Yes - you are right! It was an misunderstanding. Thank you for your hint!!
