### ISSUE TITLE
register_notification_object

### ISSUE THREAD

**Issue by TheMuller** [ColdTrick/blog_tools#25]
When saving a new blog post in blog tools version 2.5 in Elgg version 1.10 I get the following message:
**register_notification_object** depricated by **elgg_register_notification_event**

**Comment by SirbitoX** [comment]
use the latest version of blog tools. download it from git or the link below: 
https://community.elgg.org/plugins/782529

**Comment by jdalsem** [comment]
This is fixed in a newer version
