### ISSUE TITLE
sending notificaton when a post published

### ISSUE THREAD

**Issue by SirbitoX** [ColdTrick/blog_tools#29]
Hi, 

In save action of blog plugin an event triggers when a post is published. but this event doesn't triggers 
for the blog published with advanced publication options (e.g. cron).

So we need a change on ``` \classes\ColdTrick\BlogTools\Cron.php ```:
```php
...
// set correct time created
$entity->time_created = $time;

// publish blog
$entity->status = "published";

// send notifications when post published
elgg_trigger_event('publish', 'object', $entity);
...
```

**Comment by SirbitoX** [comment]
PR https://github.com/ColdTrick/blog_tools/pull/28

**Comment by jdalsem** [comment]
As #28 is merged this can be closed
