### ISSUE TITLE
Take care of access_id & future_access_id when publishing or expiring a blog

### ISSUE THREAD

**Issue by saeedsq** [ColdTrick/blog_tools#31]
Elgg System uses private access id in order to recognize draft blogs in blog listing.
In addition to changing blog status:
When you publish a blog via cron you should change access id of the blog to future access id
and when you expire a blog via cron you should change access id of the blog to private.

See also:
https://github.com/Elgg/Elgg/issues/8690

**Comment by siderlan** [comment]
Hi @jdalsem 

I want to know when it will be released.
Cheers!!!

**Comment by jdalsem** [comment]
Future access id is respected
