### ISSUE TITLE
when featuring a blog the wrong notification is shown

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/blog_tools#43]
if i feature a blog i see the language string:
```
blog_tools:action:toggle_metadata:success
```
which reads:
```
The entity was successfully edited
```
this should be something more relevant such as:
```
the blog was featured
```

**Comment by jeabakker** [comment]
the action was designed as a generic toggle action therefor a generic message is send to the user.

Maybe this could be changed to a message specific for the metadata which is toggled

**Comment by propertunist** [comment]
ok sure, - yes the message needs to be more specific, it is meaningless to non elgg codes ;)
