### ISSUE TITLE
Deprecated in 3.0: elgg_get_entities_from_metadata has been deprecated

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/blog_tools#48]
https://github.com/ColdTrick/blog_tools/blob/43f7cf2f8b37467e244b19d47d3be1e924b5967e/classes/ColdTrick/BlogTools/Cron.php#L83

https://github.com/ColdTrick/blog_tools/blob/43f7cf2f8b37467e244b19d47d3be1e924b5967e/classes/ColdTrick/BlogTools/Cron.php#L151

**Comment by jeabakker** [comment]
This is part of the advanced publication options which haven't been upgraded to 3.0 yet. So this isn't called

**Comment by jdalsem** [comment]
Fixed in https://github.com/ColdTrick/blog_tools/commit/e80bf4829e9cbe2a708d9366478653ffb6b0dc3c#diff-7371ae8573ebe46668be9f1d4186f2d1
