### ISSUE TITLE
Metatag Missing for Blog Image Elgg 2.3 - V 7.0.1

### ISSUE THREAD

**Issue by merilturock** [ColdTrick/blog_tools#49]
Dear Cold Trick,
        Metatag for the Blog Image is missing .. OG image option can you tell me how i can add the OG image in the code ..

**Comment by jeabakker** [comment]
I'm sorry i don't understand your question. Could you maybe explain a bit more?

**Comment by merilturock** [comment]
Hi jeabakker,
    Actually i am aware of blog tools using metatag if there is no metatag available for blog i guess it was in previous blog tools version ..

Where when we share a blog in social network..
Title , description & blog images get rendered ..
but now i only get the Title the rest is empty.. I never used any Metatag plugin's to get this work .. If i install Blog Tools all these things get generated automatically as blog tools had metatag added to blogs by default .. OG: Title, OG: Description & OG: Image    

I hope you understand what i am trying to say ..

**Comment by jdalsem** [comment]
I expect this is not an issue in blog_tools but maybe in the metatag plugin. Without more information this can not be investigated.
