### ISSUE TITLE
Blog icon image not shown in river entries

### ISSUE THREAD

**Issue by iionly** [ColdTrick/blog_tools#52]
Blog icons are no longer shown in river entries. Between blog_tools for Elgg 2.x and for 2.3 there was a change in https://github.com/ColdTrick/blog_tools/blob/master/views/default/river/object/blog/create.php resulting in the image no longer included in the body of river entries. Intential or not?

**Comment by jdalsem** [comment]
looking at the code, it might not have been intentional... will have a look at it
